# Generated by Django 4.2.16 on 2024-12-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_name_alter_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('faculty', 'Faculty'), ('admin', 'Admin'), ('superadmin', 'Superadmin')], default=None, max_length=20, null=True),
        ),
    ]
