# Generated by Django 4.2.16 on 2024-12-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_approved_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('superadmin', 'Superadmin'), ('admin', 'Admin'), ('faculty', 'Faculty'), ('student', 'Student')], default=None, max_length=20, null=True),
        ),
    ]
