# Generated by Django 4.2.16 on 2024-12-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding',
            field=models.IntegerField(default=0),
        ),
    ]
