# Generated by Django 4.2.16 on 2024-12-08 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=100)),
                ('institute_city', models.CharField(max_length=50)),
                ('institute_code', models.CharField(unique=True)),
            ],
        ),
    ]
